/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nick.gaImageRecognitionGui.panel;

import nick.gaImageRecognitionGui.util.StringConstants;
import nick.gaImageRecognitionCore.feature.Feature;
import nick.gaImageRecognitionCore.individual.Individual;
import nick.gaImageRecognitionCore.util.ConfigurationUtil;

import javax.swing.*;
import java.awt.*;
import java.util.List;

/**
 *
 * @author Nick
 */
public class JPanelVisualiseFeatures extends BasePanel {

//    private final List<Feature> featureList = null;
    private final int width = 19;
    private final int height = 19;

    /**
     * Creates new form JPanelWelkome
     * @param topPanel
     */
    public JPanelVisualiseFeatures(JPanelTopPanel topPanel) {
        super(topPanel);
        initComponents();
        jLabelConfigurationFile.setText("C:\\Users\\Nick\\workspace\\masterimagegui\\src\\main\\resources\\config\\config201608270105.txt");
//        jPanelImageFeature.setPreferredSize(new Dimension(width, height));
//        jPanelImageFeature.setMinimumSize(new Dimension(width, height));
//        this.repaint();
//        this.featureList = featureList;
//        this.width = width;
//        this.height = height;

//        paintFeatures();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabelConfigurationFile = new javax.swing.JTextField();
        jButtonSelectTrainingFolder = new javax.swing.JButton();
        jButtonVisualise = new javax.swing.JButton();
        jPanelPictureArea = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(640, 480));

        jLabel2.setText("Configuration file:");

        jLabelConfigurationFile.setEditable(false);
        jLabelConfigurationFile.setText("Not loaded..");

        jButtonSelectTrainingFolder.setText("Select..");
        jButtonSelectTrainingFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectTrainingFolderActionPerformed(evt);
            }
        });

        jButtonVisualise.setText("Visualise");
        jButtonVisualise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisualiseActionPerformed(evt);
            }
        });

        jPanelPictureArea.setMinimumSize(new java.awt.Dimension(600, 300));
        jPanelPictureArea.setPreferredSize(new java.awt.Dimension(600, 300));

        javax.swing.GroupLayout jPanelPictureAreaLayout = new javax.swing.GroupLayout(jPanelPictureArea);
        jPanelPictureArea.setLayout(jPanelPictureAreaLayout);
        jPanelPictureAreaLayout.setHorizontalGroup(
            jPanelPictureAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelPictureAreaLayout.setVerticalGroup(
            jPanelPictureAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelPictureArea, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonSelectTrainingFolder)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(130, 130, 130)
                                .addComponent(jButtonVisualise))
                            .addComponent(jLabelConfigurationFile, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(232, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanelPictureArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButtonSelectTrainingFolder)
                    .addComponent(jButtonVisualise))
                .addGap(18, 18, 18)
                .addComponent(jLabelConfigurationFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSelectTrainingFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectTrainingFolderActionPerformed
        JFileChooser fc = new JFileChooser();

        fc.setCurrentDirectory(new java.io.File("."));
        fc.setDialogTitle(StringConstants.SELECT_TRAINING_FOLDER);
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fc.setAcceptAllFileFilterUsed(false);

        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            String path = fc.getSelectedFile().getAbsolutePath();
//            String path = fc.getSelectedFile().getPath();
//            RuntimeConfiguration.getInstance().setTrainingFolderPath(path);
            jLabelConfigurationFile.setText(path);
//            jLabelConfigurationFile.setText(path);
        } else {
//            String path = RuntimeConfiguration.getInstance().getTrainingFolderPath();
//            if (StringUtils.isNotBlank(path)) {
//                jLabelConfigurationFile.setText(path);
//            }
        }
    }//GEN-LAST:event_jButtonSelectTrainingFolderActionPerformed

    private void jButtonVisualiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisualiseActionPerformed
        Individual[] individuals = ConfigurationUtil.readConfiguration(jLabelConfigurationFile.getText());

        List<Feature> features = individuals[0].getFeatureList();

        JPanelPrintFeatures imagePanel = new JPanelPrintFeatures(features, width, height);

        jPanelPictureArea.removeAll();
        jPanelPictureArea.setLayout(new BorderLayout());
        jPanelPictureArea.add(imagePanel, BorderLayout.CENTER);
        jPanelPictureArea.revalidate();
        jPanelPictureArea.repaint();
//        topPanel.revalidate();
//        topPanel.repaint();

    }//GEN-LAST:event_jButtonVisualiseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSelectTrainingFolder;
    private javax.swing.JButton jButtonVisualise;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jLabelConfigurationFile;
    private javax.swing.JPanel jPanelPictureArea;
    // End of variables declaration//GEN-END:variables
    @Override
    void initLabelValues() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

//    @Override
//    public void paint(Graphics g) {
//        g.setColor(Color.BLACK);
//        super.paint(g);
//        
//        for (Feature feature : featureList) {
//            Rect location = feature.getPositionInPicture();
////            g.draw3DRect(location);
//            g.drawRect(location.getMinX(), location.getMinY(), location.getWidth(), location.getHeight());
////            g.drawLine(location.getMinX(), WIDTH, WIDTH, WIDTH);
////            g.drawLine(WIDTH, WIDTH, WIDTH, WIDTH);
//        }
//
//        // define the position
////        int locX = 200;
////        int locY = 200;
//
//        // draw a line (there is no drawPoint..)
////        g.drawLine(locX, locY, locX, locY);
//    }
//    private void paintFeatures() {
//        for (Feature featureList1 : featureList) {
//            paint(null);
//        }
//    }
}
