/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nick.gaImageRecognitionGui.run;

import nick.gaImageRecognitionGui.panel.*;
import nick.gaImageRecognitionGui.util.Util;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Nick
 */
public class JFrameStart extends javax.swing.JFrame {

    private JPanel activePanel;
    private final JPanelTopPanel topPanel;

    /**
     * Creates new form Srart
     */
    public JFrameStart() {
        initComponents();
        setLayout(new BorderLayout());

        //add top panel
        topPanel = new JPanelTopPanel();
        add(topPanel, BorderLayout.CENTER);

        JPanelWelcome welcome = new JPanelWelcome(topPanel);
        setActivePanel(welcome);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemTraining = new javax.swing.JMenuItem();
        jMenuItemTestSavedConf = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jMenu2.setText("Run");

        jMenuItemTraining.setText("Training");
        jMenuItemTraining.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTrainingActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemTraining);

        jMenuItemTestSavedConf.setText("Test Trained Conf");
        jMenuItemTestSavedConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTestSavedConfActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemTestSavedConf);

        jMenuItem1.setText("Visualise Features");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Help");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Start Page");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("About");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 622, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemTrainingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTrainingActionPerformed
        JPanelTraining jPanelTraining = new JPanelTraining(topPanel);
        setActivePanel(jPanelTraining);
    }//GEN-LAST:event_jMenuItemTrainingActionPerformed

    private void jMenuItemTestSavedConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTestSavedConfActionPerformed
        JPanelTestSavedConfiguration jPanelTestSavedConfiguration = new JPanelTestSavedConfiguration(topPanel);
        setActivePanel(jPanelTestSavedConfiguration);
    }//GEN-LAST:event_jMenuItemTestSavedConfActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JPanelVisualiseFeatures jPanelVisualiseFeatures = new JPanelVisualiseFeatures(topPanel);
         setActivePanel(jPanelVisualiseFeatures);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JPanelWelcome jPanelWelcome = new JPanelWelcome(topPanel);
        setActivePanel(jPanelWelcome);
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JPanelAbout jPanelAbout = new JPanelAbout(topPanel);
        setActivePanel(jPanelAbout);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void setActivePanel(JPanel panel) {
        Util.centreWindow(this);

        panel.setSize(640, 480);
        if (activePanel != null) {
            topPanel.remove(activePanel);
        }
        activePanel = panel;

        topPanel.add(panel, BorderLayout.CENTER);

        topPanel.revalidate();
        topPanel.repaint();

        this.pack();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemTestSavedConf;
    private javax.swing.JMenuItem jMenuItemTraining;
    // End of variables declaration//GEN-END:variables
}
